--EJERCICIOS GRAFICOS A TEXTO

-------------------------------EJERCICIO 1-------------------------------
CREATE DATABASE EJE1
GO
USE EJE1
GO

CREATE TABLE DUENYOS(
	DNI			CHAR(10)		NOT NULL,
	nombre		VARCHAR(100)	NOT NULL,
	apellido1	VARCHAR(100)	NOT NULL,
	apellido2	VARCHAR(100),
	direccion	VARCHAR(200)	NOT NULL,

	CONSTRAINT PK_DNI PRIMARY KEY (DNI)
)
GO
CREATE TABLE COCHES(
	matricula	CHAR(10)		NOT NULL,
	marca		VARCHAR(100)	NOT NULL,
	modelo		VARCHAR(100)	NOT NULL,
	DNI_DUENYO	CHAR(10),

	CONSTRAINT PK_MATRICULA PRIMARY KEY (matricula),
	CONSTRAINT PK_COCHES_DUENYO FOREIGN KEY (DNI_duenyo) REFERENCES DUENYOS(DNI)
)


-------------------------------EJERCICIO 2-------------------------------
CREATE DATABASE EJE2
GO
USE EJE2
GO

CREATE TABLE PROVEEDORES(
	idProv		INT IDENTITY(1,1)	NOT NULL,
	nombre		VARCHAR(100)		NOT NULL,
	direccion	VARCHAR(100)		NOT NULL,

	CONSTRAINT PK_PROVEEDORES PRIMARY KEY (idProv),
)
GO
CREATE TABLE ARTICULOS(
	idArticulo		INT IDENTITY(1,1)	NOT NULL,
	nombre			VARCHAR(100)		NOT NULL,
	descripcion		VARCHAR(1000),
	precio			DECIMAL(9,2)		NOT NULL,
	existencias		DECIMAL(5,0)		NOT NULL,

	CONSTRAINT PK_ARTICULOS PRIMARY KEY (idArticulo),
	CONSTRAINT CK_ARTICULOS_PRECIO CHECK (precio>0),
	CONSTRAINT CK_ARTICULOS_EXISTENCIAS CHECK (existencias>=0),
)
GO
CREATE TABLE SUMINISTROS(
	idProv				INT				NOT NULL,
	idArticulo			INT				NOT NULL,
	unidades			DECIMAL(5,0)	NOT NULL,
	fechaRecepcion		SMALLDATETIME,

	CONSTRAINT PK_SUMINISTROS PRIMARY KEY (idProv, idArticulo),
	CONSTRAINT FK_SUMINISTROS_PROVEEDORES FOREIGN KEY (idProv) REFERENCES PROVEEDORES(idProv),
	CONSTRAINT FK_SUMINISTROS_ARTICULOS FOREIGN KEY (idArticulo) REFERENCES ARTICULOS(idArticulo),
	CONSTRAINT CK_SUMINISTROS_UNIDADES CHECK (unidades>=0),
)

-------------------------------EJERCICIO 3-------------------------------
CREATE DATABASE EJE3
GO
USING EJE3
GO

CREATE TABLE TEMAS(
	idTema		INT IDENTITY(1,1)	NOT NULL,
	nombre		VARCHAR(100)		NOT NULL,

	CONSTRAINT PK_TEMAS PRIMARY KEY(idTema)
)
GO

CREATE TABLE LIBROS(
	ISBN			CHAR(13)		NOT NULL,
	titulo			VARCHAR(100)	NOT NULL,
	autor			VARCHAR(200),
	numEjemplares	DECIMAL(5,0)	NOT NULL,
	idTema			INT				NOT NULL,

	CONSTRAINT PK_LIBROS PRIMARY KEY(ISBN),
	CONSTRAINT FK_LIBROS_TEMAS FOREIGN KEY(idTema) REFERENCES TEMAS(idTema)
)
GO

CREATE TABLE SOCIOS(
	DNI			CHAR(9)			NOT NULL,
	nombre		VARCHAR(100)	NOT NULL,
	direccion	VARCHAR(200)	NOT NULL,
	fechaAlta	SMALLDATETIME	NOT NULL,
	fechaBaja	SMALLDATETIME,

	CONSTRAINT PK_SOCIOS PRIMARY KEY(DNI)
)
GO

CREATE TABLE TELEFONOS_SOCIOS(
	DNI			INT			NOT NULL,
	telefono	CHAR(9)		NOT NULL,

	CONSTRAINT PK_TELEFONOS_SOCIOS PRIMARY KEY(DNI, telefono)
)
GO

CREATE TABLE PRESTAMOS(
	DNI					INT				NOT NULL,
	ISBN				CHAR(13)		NOT NULL,
	fechaPrestamo		SMALLDATETIME	NOT NULL,
	fechaDevolucion		SMALLDATETIME,

	CONSTRAINT PK_PRESTAMOS PRIMARY KEY(DNI, ISBN, fechaPrestamo)
	CONSTRAINT FK_PRESTAMOS_SOCIOS FOREIGN KEY(DNI) REFERENCES SOCIOS(DNI)
	CONSTRAINT FK_PRESTAMOS_LIBROS FOREIGN KEY(ISBN) REFERENCES LIBROS(ISBN)
)