-- Ejercicio 4.2 DDL:

---------------------------------------Ejercicio 1---------------------------------------

CREATE DATABASE EJE4.2.1
GO
USE EJE4.2.1

GO

CREATE TABLE GALERIA (
	idGaleria		INT IDENTITY	NOT NULL, 
	nombre			VARCHAR(100)	NOT NULL,
	ciudad			VARCHAR(200)	NOT NULL,
	direcion		VARCHAR(400)	NOT NULL,
	metrosCuadrado	DECIMAL(6,2),

	CONSTRAINT PK_GALERIA PRIMARY KEY (idGaleria)
)

GO

CREATE TABLE ESCUELA (
	idEscuela	INT IDENTITY	NOT NULL,
	nombre		VARCHAR(100)	NOT NULL,
	pais		VARCHAR(100)	NOT NULL,
	fechaAlta	SMALLDATETIME	NOT NULL,

	CONSTRAINT PK_ESCUELA PRIMARY KEY (idEscuela)
)

GO

CREATE TABLE PINTOR (
	idPintor			INT IDENTITY	NOT NULL,
	nombre				VARCHAR(100)	NOT NULL,
	pais				VARCHAR(100),
	idPintorMaestro		INT				NOT NULL,
	idEscuela			INT				NOT NULL,

	CONSTRAINT PK_PINTOR PRIMARY KEY (idPintor),
	CONSTRAINT FK_PINTOR FOREIGN KEY (idPintorMaestro) REFERENCES PINTOR (idPintor),
	CONSTRAINT FK_PINTOR_ESCUELA FOREIGN KEY (idEscuela) REFERENCES ESCUELA (idEscuela),
)

GO

CREATE INDEX IX_PINTOR ON PINTOR (nombre)

GO

CREATE TABLE PATROCINADOR (
	idPatrocinador		INT IDENTITY	NOT NULL,
	nombre				VARCHAR(100)	NOT NULL,
	pais				VARCHAR(100),

	CONSTRAINT PK_PATROCINADOR PRIMARY KEY (idPatrocinador)
)

GO

CREATE TABLE CUADRO (
	idCuadro		INT IDENTITY	NOT NULL,
	dimensionesx	DECIMAL(5,2)	NOT NULL,
	dimensionesy	DECIMAL(5,2)	NOT NULL,
	fecha			SMALLDATETIME,
	tecnica			VARCHAR(200),
	idGaleria		INT,
	idPintor		INT,

	CONSTRAINT PK_CUADRO PRIMARY KEY (idCuadro),
	CONSTRAINT FK_CUADROS_GALERIA FOREIGN KEY (idGaleria) REFERENCES GALERIA (idGaleria),
	CONSTRAINT FK_CUADORS_PINTOR FOREIGN KEY (idPintor) REFERENCES PINTOR (idPintor)
)

GO

CREATE TABLE PATROCINADOR_MECENAS (
	idPintor			INT		NOT NULL,
	idPatrocinador		INT		NOT NULL,

	CONSTRAINT PK_PATROCINADOR_MECENAS PRIMARY KEY (idPintor, idPatrocinador),
	CONSTRAINT FK_PATROCINADOR_MECENAS_PINTORES FOREIGN KEY (idPintor) REFERENCES PINTOR (idPintor),
	CONSTRAINT FK_PATROCINADOR_MECENAS_PATROCINADORES FOREIGN KEY (idPatrocinador) REFERENCES PATROCINADOR (idPatrocinador)
)

---------------------------------------Ejercicio 2---------------------------------------

CREATE TABLE PROVINCIA (
	idProvincia		INT IDENTITY	NOT NULL,
	nombre			VARCHAR(200)	NOT NULL,

	CONSTRAINT PK_PROVINCIA PRIMARY KEY (idProvincia)
)

GO

CREATE TABLE MUNICIPIO (
	idProvincia		INT,			NOT NULL,
	idMunicipio		INT IDENTITY	NOT NULL,
	nombre			VARCHAR(200)	NOT NULL,

	CONSTRAINT PK_MUNICIPIO PRIMARY KEY (idProvincia, idMunicipio),
	CONSTRAINT FK_MUNICIPIO_PROVINCIA FOREIGN KEY (idProvincia) REFERENCES PROVINCIA(idProvincia)
)

GO

CREATE TABLE IMPUESTOS (
	idImpuesto		INT IDENTITY	NOT NULL,
	importe			DECIMAL(6,2)	NOT NULL,
	fechaMaxPago	SMALLDATETIME	NOT NULL,
	ano				CHAR(4),

	CONSTRAINT PK_IMPUESTOS PRIMARY KEY (idImpuesto)
)

GO

CREATE TABLE IBI (
	idImpuestoIBI	INT				NOT NULL,
	valCatastral	NUMERIC(19,2)	NOT NULL,
	tipoImpositivo	DECIMAL(5,2)	NOT NULL,

	CONSTRAINT PK_IBI PRIMARY KEY (idImpuestoIBI),
	CONSTRAINT FK_IBI_IMPUESTOS FOREIGN KEY (idImpuestoIBI) REFERENCES IMPUESTOS (idImpuesto)
)

GO

CREATE TABLE IVTM (
	idImpuestoIVTM		INT				NOT NULL,
	tipoVehiculo		VARCHAR(40),
	cFiscales			DECIMAL(4,2),

	CONSTRAINT PK_IVTM PRIMARY KEY (idImpuestoIVTM),
	CONSTRAINT FK_IVTM_IMPUESTOS FOREIGN KEY (idImpuestoIVTM) REFERENCES IMPUESTOS (idImpuesto)
)

GO

CREATE TABLE IAE (
	idIAE			INT				NOT NULL,
	factMediaAnual	NUMERIC(19,2)	NOT NULL,

	CONSTRAINT PK_IAE PRIMARY KEY (idIAE),
	CONSTRAINT FK_IAE_IMPUESTOS FOREIGN KEY (idIAE) REFERENCES IMPUESTOS (idImpuesto)
)

GO

CREATE TABLE CONTRIBUYENTES (
	NIF			CHAR(9)			NOT NULL,
	nombre		VARCHAR(100)	NOT NULL,
	apellido1	VARCHAR(100)	NOT NULL,
	apellido2	VARCHAR(100),
	direccion	VARCHAR(200)	NOT NULL,
	codPostal	CHAR(5)			NOT NULL,

	CONSTRAINT PK_CONTRIBUYENTES PRIMARY KEY (NIF)
)

GO

CREATE TABLE OFICINAS (
	idOficina	INT IDENTITY	NOT NULL,
	nombre		VARCHAR(100)	NOT NULL,
	direccion	VARCHAR(200)	NOT NULL,

	CONSTRAINT PK_OFICINAS PRIMARY KEY (idOficina)
)

GO

CREATE TABLE CONTRIBUYENTES_IMPUESTOS_OFICINAS (
	idImpuestoPaga		INT				NOT NULL,
	NIFPaga				CHAR(9),
	fechaHora			SMALLDATETIME	NOT NULL,
	modoPago			VARCHAR(20)		NOT NULL,
	idOficinaPaga		INT				NOT NULL,

	CONSTRAINT PK_CONTRIBUYENTES_IMPUESTOS_OFICINAS PRIMARY KEY (idImpuestoPaga, NIFPaga),
	CONSTRAINT FK_CONTRIBUYENTES_IMPUESTOS_OFICINAS_IMPUESTOS FOREIGN KEY (idImpuestoPaga) REFERENCES IMPUESTOS (idImpuesto),
	CONSTRAINT FK_CONTRIBUYENTES_IMPUESTOS_OFICINAS_CONTRIBUYENTES FOREIGN KEY (NIFPaga) REFERENCES CONTRIBUYENTES (NIF),
	CONSTRAINT FK_CONTRIBUYENTES_IMPUESTOS_OFICINAS_OFICINAS FOREIGN KEY (idOficinaPaga) REFERENCES OFICINAS (idOficina)
)

---------------------------------------Ejercicio 3---------------------------------------

CREATE TABLE CATEGORIAS (
	idCategoria	INT IDENTITY		NOT NULL,
	nombre			VARCHAR(100)	NOT NULL,
	IVA				DECIMAL(3,2)	NOT NULL,

	CONSTRAINT PK_CATEGORIAS PRIMARY KEY (idCategoria)
)

GO

CREATE TABLE CLIENTES (
	idCliente		INT IDENTITY	NOT NULL,
	nombre			VARCHAR(100)	NOT NULL,
	direccion		VARCHAR(200)	NOT NULL,
	telefono		CHAR(9)			NOT NULL,

	CONSTRAINT PK_CLIENTES PRIMARY KEY (idCliente)
)

GO

CREATE TABLE PARTICULARES (
	idClienteParticular		INT			NOT NULL,
	DNI						CHAR(9)		NOT NULL,

	CONSTRAINT PK_PARTICULARES PRIMARY KEY (idClienteParticular),
	CONSTRAINT FK_PARTICULARES_CLIENTES FOREIGN KEY (idClienteParticular) REFERENCES CLIENTES (idCliente)
)

GO

CREATE TABLE AGENCIAS (
	idClienteAgencia	INT				NOT NULL,
	nomAgencia			VARCHAR(100)	NOT NULL,

	CONSTRAINT PK_AGENCIAS PRIMARY KEY (idClienteAgencia),
	CONSTRAINT FK_AGENCIAS_CLIENTES FOREIGN KEY (idClienteAgencia) REFERENCES CLIENTES (idCliente)
)

GO

CREATE TABLE HOTELES (
	idHotel				INT IDENTITY	NOT NULL,
	nombre				VARCHAR(100)	NOT NULL,
	direccion			VARCHAR(250)	NOT NULL,
	telefono			CHAR(9)			NOT NULL,
	idCategoriaHotel	INT,

	CONSTRAINT PK_HOTELES PRIMARY KEY (idHotel),
	CONSTRAINT FK_HOTELES_CATEGORIAS FOREIGN KEY (idCategoriaHotel) REFERENCES CATEGORIAS (idCategoria)
)

GO

CREATE TABLE HABITACIONES (
	idHotelHabitacion	INT				NOT NULL,
	idHabitacion		INT IDENTITY	NOT NULL,
	tipoHabitacion		VARCHAR(50)		NOT NULL,
	precio				DECIMAL(6,2)	NOT NULL,

	CONSTRAINT PK_HABITACIONES PRIMARY KEY (idHotelHabitacion, idHabitacion),
	CONSTRAINT FK_HABITACIONES_HOTELES FOREIGN KEY (idHotelHabitacion) REFERENCES HOTELES (idHotel)
)

GO

CREATE TABLE RESERVAS (
	idReserva				INT IDENTITY	NOT NULL,
	idHotelReserva			INT				NOT NULL,
	idHabitacionReserva		INT				NOT NULL,
	idClienteReserva		INT				NOT NULL,
	fechaInicio				SMALLDATETIME	NOT NULL,
	fechaFin				SMALLDATETIME	NOT NULL,
	precioTotal				DECIMAL(6,2)	NOT NULL,

	CONSTRAINT PK_RESERVAS PRIMARY KEY (idReserva),
	CONSTRAINT FK_RESERVAS_HABITACIONES FOREIGN KEY (idHotelReserva, idHabitacionReserva) REFERENCES HABITACIONES (idHotelHabitacion, idHabitacion),
	CONSTRAINT FK_RESERVAS_CLIENTES FOREIGN KEY (idClienteReserva) REFERENCES CLIENTES (idCliente),
)