name: Push Programado

on:
  schedule:
    - cron: '0 0,14,21 * * *' # Ejecutar a medianoche (0), 2:30 PM (14), y 9 PM (21) en UTC

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar Git
        run: |
          git config --global user.name "Tu Nombre"
          git config --global user.email "tu@email.com"

      - name: Realizar Push
        run: |
          current_hour=$(date +'%H')
          if [ $current_hour -eq 0 ] || [ $current_hour -eq 14 ] || [ $current_hour -eq 21 ]; then
            git commit -am "Push programado"
            git push
          else
            echo "No es una hora programada para push."
          fi
